### ISSUE TITLE
Killed due to memory issue

### ISSUE THREAD

**Issue by MoriZSJ** [BIT-DA/TSA#4]
Thanks a lot for releasing the code. Your work is fabulous!

While I tried to reproduce the results, I noticed that the program would occupy more and more memory (~3G/epoch, with num_worker adjusted to 1) and got killed by the machine later. I am running Office31 experiments and I believe this memory issue is rooted in the code maybe. 

My environment is almost the same as required except that my torchvision is 0.5.0.

Could you please give me some clue to tackle this? Thanks in advance!

**Comment by kxgong** [comment]
Hi, Im wondering that "more and more memory" means "GPU memory" or just "memory"?

**Comment by MoriZSJ** [comment]
Memory.

**Comment by kxgong** [comment]
> Memory.

Maybe you can try to set ```num_worker``` as 0？

**Comment by MoriZSJ** [comment]
> > Memory.
> 
> Maybe you can try to set `num_worker` as 0？

Thanks for your response. I will close this issue for now and reopen it if the same problem remains. : )

**Comment by kxgong** [comment]
Good luck！
